export type CatalogSeedUnit = "st" | "kg" | "g" | "l" | "dl" | "ml" | "pkt" | "burk";

export interface CatalogSeedItem {
  id: string;
  name: string;
  category: string;
  defaultQuantity: number;
  defaultUnit: CatalogSeedUnit;
  units: CatalogSeedUnit[];
}

function slugify(value: string): string {
  return value
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function seed(category: string, name: string, defaultUnit: CatalogSeedUnit): CatalogSeedItem {
  return {
    id: slugify(`${category}-${name}`),
    name,
    category,
    defaultQuantity: 1,
    defaultUnit,
    units: [defaultUnit],
  };
}

export const DEFAULT_CATEGORIES = [
  "Frukt & grönt",
  "Mejeri",
  "Kylvaror",
  "Frys",
  "Skafferi",
  "Dryck",
  "Snacks",
  "Toa & Badrum",
  "Kök",
  "Barn",
  "Djur",
];

export const SEED_CATALOG: CatalogSeedItem[] = [
  seed("Frukt & grönt", "Banan", "kg"),
  seed("Frukt & grönt", "Äpple", "kg"),
  seed("Frukt & grönt", "Päron", "kg"),
  seed("Frukt & grönt", "Apelsin", "kg"),
  seed("Frukt & grönt", "Vindruvor", "kg"),
  seed("Frukt & grönt", "Jordgubbar", "kg"),
  seed("Frukt & grönt", "Hallon", "kg"),
  seed("Frukt & grönt", "Blåbär", "kg"),
  seed("Frukt & grönt", "Tomat", "kg"),
  seed("Frukt & grönt", "Potatis", "kg"),
  seed("Frukt & grönt", "Morot", "kg"),
  seed("Frukt & grönt", "Palsternacka", "kg"),
  seed("Frukt & grönt", "Rödbeta", "kg"),
  seed("Frukt & grönt", "Gul lök", "kg"),
  seed("Frukt & grönt", "Röd lök", "kg"),
  seed("Frukt & grönt", "Citron", "st"),
  seed("Frukt & grönt", "Lime", "st"),
  seed("Frukt & grönt", "Avokado", "st"),
  seed("Frukt & grönt", "Mango", "st"),
  seed("Frukt & grönt", "Ananas", "st"),
  seed("Frukt & grönt", "Kiwi", "st"),
  seed("Frukt & grönt", "Gurka", "st"),
  seed("Frukt & grönt", "Paprika", "st"),
  seed("Frukt & grönt", "Broccoli", "st"),
  seed("Frukt & grönt", "Blomkål", "st"),
  seed("Frukt & grönt", "Zucchini", "st"),
  seed("Frukt & grönt", "Aubergine", "st"),
  seed("Frukt & grönt", "Isbergssallad", "st"),
  seed("Frukt & grönt", "Vitkål", "st"),
  seed("Frukt & grönt", "Rödkål", "st"),
  seed("Frukt & grönt", "Vitlök", "st"),
  seed("Frukt & grönt", "Ingefära", "st"),
  seed("Frukt & grönt", "Chili", "st"),
  seed("Frukt & grönt", "Champinjoner", "pkt"),
  seed("Frukt & grönt", "Körsbärstomater", "pkt"),
  seed("Frukt & grönt", "Ruccola", "pkt"),
  seed("Frukt & grönt", "Babyspenat", "pkt"),
  seed("Frukt & grönt", "Salladsmix", "pkt"),
  seed("Frukt & grönt", "Färska örter", "pkt"),
  seed("Mejeri", "Mjölk", "l"),
  seed("Mejeri", "Havredryck", "l"),
  seed("Mejeri", "Yoghurt", "l"),
  seed("Mejeri", "Fil", "l"),
  seed("Mejeri", "Grädde", "l"),
  seed("Mejeri", "Smör", "pkt"),
  seed("Mejeri", "Margarin", "pkt"),
  seed("Mejeri", "Ägg", "pkt"),
  seed("Mejeri", "Riven ost", "pkt"),
  seed("Mejeri", "Mozzarella", "pkt"),
  seed("Mejeri", "Fetaost", "pkt"),
  seed("Mejeri", "Halloumi", "pkt"),
  seed("Mejeri", "Kvarg", "pkt"),
  seed("Mejeri", "Keso", "pkt"),
  seed("Mejeri", "Crème fraiche", "pkt"),
  seed("Mejeri", "Hårdost", "kg"),
  seed("Kylvaror", "Bacon", "pkt"),
  seed("Kylvaror", "Falukorv", "pkt"),
  seed("Kylvaror", "Korv", "pkt"),
  seed("Kylvaror", "Skinka", "pkt"),
  seed("Kylvaror", "Salami", "pkt"),
  seed("Kylvaror", "Leverpastej", "pkt"),
  seed("Kylvaror", "Köttbullar färska", "pkt"),
  seed("Kylvaror", "Hamburgare färska", "pkt"),
  seed("Kylvaror", "Pastasallad", "pkt"),
  seed("Kylvaror", "Potatissallad", "pkt"),
  seed("Kylvaror", "Hummus", "pkt"),
  seed("Kylvaror", "Tzatziki", "pkt"),
  seed("Kylvaror", "Pesto", "pkt"),
  seed("Kylvaror", "Färsk pasta", "pkt"),
  seed("Kylvaror", "Kycklingfilé", "kg"),
  seed("Kylvaror", "Nötfärs", "kg"),
  seed("Kylvaror", "Blandfärs", "kg"),
  seed("Kylvaror", "Fläskfärs", "kg"),
  seed("Kylvaror", "Laxfilé", "kg"),
  seed("Kylvaror", "Torskfilé", "kg"),
  seed("Frys", "Kycklingfilé fryst", "kg"),
  seed("Frys", "Kycklinglår fryst", "kg"),
  seed("Frys", "Hel kyckling fryst", "kg"),
  seed("Frys", "Nötfärs fryst", "kg"),
  seed("Frys", "Laxfilé fryst", "kg"),
  seed("Frys", "Torskfilé fryst", "kg"),
  seed("Frys", "Räkor frysta", "kg"),
  seed("Frys", "Köttbullar frysta", "pkt"),
  seed("Frys", "Hamburgare frysta", "pkt"),
  seed("Frys", "Fiskpinnar", "pkt"),
  seed("Frys", "Wokgrönsaker frysta", "pkt"),
  seed("Frys", "Broccoli fryst", "pkt"),
  seed("Frys", "Ärtor frysta", "pkt"),
  seed("Frys", "Majs fryst", "pkt"),
  seed("Frys", "Frysta hallon", "pkt"),
  seed("Frys", "Frysta blåbär", "pkt"),
  seed("Frys", "Frysta jordgubbar", "pkt"),
  seed("Frys", "Pommes frites", "pkt"),
  seed("Frys", "Fryst pizza", "pkt"),
  seed("Frys", "Vegoburgare frysta", "pkt"),
  seed("Frys", "Glass", "pkt"),
  seed("Frys", "Glasspinnar", "pkt"),
  seed("Frys", "Lasagne fryst", "pkt"),
  seed("Frys", "Paj fryst", "pkt"),
  seed("Skafferi", "Ris", "kg"),
  seed("Skafferi", "Havregryn", "kg"),
  seed("Skafferi", "Vetemjöl", "kg"),
  seed("Skafferi", "Rågmjöl", "kg"),
  seed("Skafferi", "Socker", "kg"),
  seed("Skafferi", "Salt", "kg"),
  seed("Skafferi", "Linser", "kg"),
  seed("Skafferi", "Pasta", "pkt"),
  seed("Skafferi", "Spaghetti", "pkt"),
  seed("Skafferi", "Makaroner", "pkt"),
  seed("Skafferi", "Couscous", "pkt"),
  seed("Skafferi", "Bulgur", "pkt"),
  seed("Skafferi", "Quinoa", "pkt"),
  seed("Skafferi", "Krossade tomater", "pkt"),
  seed("Skafferi", "Tomatpuré", "pkt"),
  seed("Skafferi", "Tonfisk", "pkt"),
  seed("Skafferi", "Kikärtor", "pkt"),
  seed("Skafferi", "Bönor", "pkt"),
  seed("Skafferi", "Kokosmjölk", "pkt"),
  seed("Skafferi", "Buljong", "pkt"),
  seed("Skafferi", "Ketchup", "pkt"),
  seed("Skafferi", "Senap", "pkt"),
  seed("Skafferi", "Majonnäs", "pkt"),
  seed("Skafferi", "BBQ-sås", "pkt"),
  seed("Skafferi", "Sojasås", "pkt"),
  seed("Skafferi", "Tacokrydda", "pkt"),
  seed("Skafferi", "Olivolja", "l"),
  seed("Skafferi", "Rapsolja", "l"),
  seed("Skafferi", "Honung", "pkt"),
  seed("Skafferi", "Sirap", "pkt"),
  seed("Skafferi", "Sylt", "pkt"),
  seed("Skafferi", "Jordnötssmör", "pkt"),
  seed("Skafferi", "Kaffe", "pkt"),
  seed("Skafferi", "Te", "pkt"),
  seed("Skafferi", "Kryddor", "pkt"),
  seed("Dryck", "Vatten", "l"),
  seed("Dryck", "Mineralvatten", "l"),
  seed("Dryck", "Läsk", "l"),
  seed("Dryck", "Juice", "l"),
  seed("Dryck", "Saft", "l"),
  seed("Dryck", "Energidryck", "st"),
  seed("Dryck", "Iskaffe", "st"),
  seed("Snacks", "Chips", "pkt"),
  seed("Snacks", "Ostbågar", "pkt"),
  seed("Snacks", "Popcorn", "pkt"),
  seed("Snacks", "Nötter", "pkt"),
  seed("Snacks", "Riskakor", "pkt"),
  seed("Snacks", "Kex", "pkt"),
  seed("Snacks", "Chokladkaka", "pkt"),
  seed("Snacks", "Lakrits", "pkt"),
  seed("Snacks", "Godis", "kg"),
  seed("Snacks", "Proteinbar", "st"),
  seed("Toa & Badrum", "Toalettpapper", "pkt"),
  seed("Toa & Badrum", "Hushållspapper", "pkt"),
  seed("Toa & Badrum", "Våtservetter", "pkt"),
  seed("Toa & Badrum", "Mensskydd", "pkt"),
  seed("Toa & Badrum", "Blöjor", "pkt"),
  seed("Toa & Badrum", "Plåster", "pkt"),
  seed("Toa & Badrum", "Värktabletter", "pkt"),
  seed("Toa & Badrum", "Schampo", "st"),
  seed("Toa & Badrum", "Balsam", "st"),
  seed("Toa & Badrum", "Duschgel", "st"),
  seed("Toa & Badrum", "Deo", "st"),
  seed("Toa & Badrum", "Tandkräm", "st"),
  seed("Toa & Badrum", "Tandborste", "st"),
  seed("Toa & Badrum", "Handtvål", "st"),
  seed("Toa & Badrum", "Hudkräm", "st"),
  seed("Kök", "Diskmaskinstabletter", "pkt"),
  seed("Kök", "Disktrasor", "pkt"),
  seed("Kök", "Svampar", "pkt"),
  seed("Kök", "Soppåsar", "pkt"),
  seed("Kök", "Fryspåsar", "pkt"),
  seed("Kök", "Plastfolie", "pkt"),
  seed("Kök", "Aluminiumfolie", "pkt"),
  seed("Kök", "Bakplåtspapper", "pkt"),
  seed("Kök", "Servetter", "pkt"),
  seed("Kök", "Batterier", "pkt"),
  seed("Kök", "Tvättmedel", "pkt"),
  seed("Kök", "Diskmedel", "st"),
  seed("Kök", "Allrengöring", "st"),
  seed("Kök", "Fönsterputs", "st"),
  seed("Kök", "Sköljmedel", "st"),
  seed("Barn", "Välling", "pkt"),
  seed("Barn", "Ersättning", "pkt"),
  seed("Barn", "Barnmat", "pkt"),
  seed("Barn", "Våtservetter barn", "pkt"),
  seed("Barn", "Napp", "st"),
  seed("Djur", "Hundmat", "pkt"),
  seed("Djur", "Kattmat", "pkt"),
  seed("Djur", "Kattsand", "pkt"),
  seed("Djur", "Hundgodis", "pkt"),
  seed("Djur", "Kattgodis", "pkt"),
];
